name: medicare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7096
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  flutter_riverpod: ^2.4.9
  cached_network_image: ^3.3.1
  http: ^1.2.1                    # Backend API calls ke liye
  shared_preferences: ^2.2.2      # JWT token local storage ke liye
  webview_flutter: ^4.7.0         # Embedded video/meeting UI
  url_launcher: ^6.3.1            # Open Jitsi in browser on web/desktop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
